### ISSUE TITLE
Update mods in a non-standard location?

### ISSUE THREAD

**Issue by wMarciano** [syorito-hatsuki/ducky-updater-rework#12]
Firstly, thank you for this mod! Works wonderfully.

Would it be possible to add in functionality for updating mods outside of the typical /mods/ directory? My specific use case is on a server, using automodpack to easily provide a modpack to my friends (at a directory like /automodpack/host-modpack/main/mods/). 

To update those mods currently, I'd have to download that directory to a local client, add the DURW mod, launch the game, do `/durw-client update all`, and then re-upload. So, the ability to do a command like `/durw-server update all "automodpack/host-modpack/main/mods/"` would be a nice time-saver.

**Comment by syorito-hatsuki** [comment]
I will think about best practice to make that, but can't give deadlines. Currently I need todo little bit more important project. I recommend to [join discord](https://discord.gg/pbwnMwnUD6) for not miss update

**Comment by asundrus** [comment]
@wMarciano as a temporarily solution, maybe could be achived with SymLinks:
https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by syorito-hatsuki** [comment]
> @wMarciano as a temporarily solution, maybe could be achived with SymLinks: https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

I'm not sure if that possible, at least for files - not, because they change own names, but maybe for folder🤔 And what if he use Windows 🤔🤔🤔

**Comment by asundrus** [comment]
Looking at the link without clicking it, that should tell you, that it's both for Windows and Linux.

**Comment by wMarciano** [comment]
I thought of something like this, but it would get so messy...all of the server mods would get mixed with the client mods, which would be potentially game breaking (for example—if the client modpack was targeting a different game version than the server is running)

**Comment by syorito-hatsuki** [comment]
So the main issue is that I get data from FabricLoader, which is required. And Fabric Loader can't take mods from other places. In my power only add the possibility to change the output folder for **new** mods, but it is going to be still in `/mods`

**Comment by syorito-hatsuki** [comment]
I will just notify that that will be in next update. But when it gonna come out not sure yet. This year at least 😉

**Comment by syorito-hatsuki** [comment]
https://modrinth.com/mod/ducky-updater-rework/version/2024.11.1
Feature exist in new version (using fabric BuildIn CLI launch arguments)
