### ISSUE TITLE
Ducky fails to fetch newest version of C2ME automatically

### ISSUE THREAD

**Issue by MyNameIsRomayne** [syorito-hatsuki/ducky-updater-rework#13]
![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/27376947/5935de2f-7cb9-43c7-a1e0-5d28b5c6b4f4)

Steps to Reproduce:

Download C2ME version 0.2.0+alpha.11.98+1.21
Check for updates
See output that suggests 0.2.0+alpha.11.104+1.21
Update all
Reboot not required, check for updates
See same output
Check folder of your server mods
![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/27376947/833e7a30-7405-4303-b9f2-a598d82a371f)
Notice there is probably a string parsing error going on (mod developers, amirite)
Manually remove the .98 version
Reboot
Check for updates
![cmd_EH5hjHk3Nc](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/27376947/f2f6b243-ef07-42ac-a535-fc0f89141848)
Checks out tbh

Expected behavior:
Same version name = Dont need to update

Notes:
I'm guessing it's the + sign and perhaps a weird character inside there doing this

**Comment by syorito-hatsuki** [comment]
I'm not sure why after the update it didn't mark itself as updated. The old version removing happens after the server restarts.

The same strings shouldn't return...

What is the mod version 
Loader
And Minecraft version

**Comment by MyNameIsRomayne** [comment]
> I'm not sure why after the update it didn't mark itself as updated. The old version removing happens after the server restarts.
> 
> The same strings shouldn't return...
> 
> What is the mod version Loader And Minecraft version

Mod filename: ducky-updater-rework-2024.5.4-1.20.jar
Loader is Fabric 0.15.11
Minecraft version is 1.21

**Comment by MyNameIsRomayne** [comment]
My guess as to why it didn't remove itself is because it wouldn't recognize the mod name due to some issues with the string somewhere down the line -- it updates the mod just fine, but seems to convert the `+` to `%2B` somewhere

**Comment by syorito-hatsuki** [comment]
> My guess as to why it didn't remove itself is because it wouldn't recognize the mod name due to some issues with the string somewhere down the line -- it updates the mod just fine, but seems to convert the `+` to `%2B` somewhere

It has 2 different registries for old and new names, that encoding issue does not affect there. I tested it many times before release.


As I see from your screenshot you didn't restart the server, you just removed it yourself. And did restart after that. If you remove files on fly (for example windows does not support that) then Minecraft is gonna crash because it's gonna lose files that it interacts on fly registered by fabric loader on boot.

I will left issue open and test E2MC later when I have time

**Comment by MyNameIsRomayne** [comment]
> > My guess as to why it didn't remove itself is because it wouldn't recognize the mod name due to some issues with the string somewhere down the line -- it updates the mod just fine, but seems to convert the `+` to `%2B` somewhere
> 
> It has 2 different registries for old and new names, that encoding issue does not affect there. I tested it many times before release.
> 
> As I see from your screenshot you didn't restart the server, you just removed it yourself. And did restart after that. If you remove files on fly (for example windows does not support that) then Minecraft is gonna crash because it's gonna lose files that it interacts on fly registered by fabric loader on boot.
> 
> I will left issue open and test E2MC later when I have time

It forbids removing files being used like that during operation, I removed the file with the server off.
(at least, in file explorer. I'm doing most server stuff manually and directly rn)

**Comment by ImBehinYa** [comment]
> y guess as to why it didn't remove itself is because it wouldn't recognize the mod name due to some issues with the string somewhere down the line -- it updates the mod just fine, but seems to convert the `+` to `%2B` somewhere

i have the same issue
Loader is Fabric 0.15.11
Minecraft version is 1.20.1
some exapmle
![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/63367722/45dd70b6-f0af-431b-82ce-b3bc6b3da24f)

![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/63367722/66786495-7e52-46c2-b56a-1f821084cec3)
 also + - swaps
 
![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/63367722/519c66d6-0ac6-4087-856d-df6edfa686bc)
the other mods are updatet via prism launcher auto updater, so ducky changes the name wierdly

**Comment by ImBehinYa** [comment]
at least it works on the server

**Comment by syorito-hatsuki** [comment]
https://github.com/syorito-hatsuki/ducky-updater-rework/issues/14

**Comment by ImBehinYa** [comment]
through the weird naming scheme the game and ducky dont reconize the mods

![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/63367722/e0c6362e-12de-4ead-a559-6db23536c3f1)

![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/63367722/2e2ffaff-ef88-4888-b3d7-02c179fad831)

![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/63367722/2ce64f27-7383-4b31-be63-0f5027a95944)
 second try also not worked
![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/63367722/168e7b50-7c05-4a40-a601-b8602f766f99)

thsi is not the only mod just as an example there are more

**Comment by syorito-hatsuki** [comment]
> through the weird naming scheme the game and ducky dont reconize the mods
> 
> ![image](https://private-user-images.githubusercontent.com/63367722/345582781-e0c6362e-12de-4ead-a559-6db23536c3f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMzQyMDYsIm5iZiI6MTcyMDAzMzkwNiwicGF0aCI6Ii82MzM2NzcyMi8zNDU1ODI3ODEtZTBjNjM2MmUtMTJkZS00ZWFkLWE1NTktNmRiMjM1MzZjM2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE5MTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMTM0ZTNiMGZjOGZhNWEwNWI5M2Q0MTM3ZTQ5NDNiZGNjNzIzNDU5YWRlNmNlZWY5MjE5NDZlNzhjODI2ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ibr9TJWLl5xOzi5oj7vAv0fxZU49AyZbUCNHXrxPp3s)
> 
> ![image](https://private-user-images.githubusercontent.com/63367722/345582842-2e2ffaff-ef88-4888-b3d7-02c179fad831.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMzQyMDYsIm5iZiI6MTcyMDAzMzkwNiwicGF0aCI6Ii82MzM2NzcyMi8zNDU1ODI4NDItMmUyZmZhZmYtZWY4OC00ODg4LWIzZDctMDJjMTc5ZmFkODMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE5MTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNzc1ZjY1NWUzM2RmYWU5ZjZjYWFhYTllYmM1MGZmN2QyNzBkNWJiYzM5N2NjNmYzNzY0ODMzNGQ1ZmJiYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uh3MgWe5c8R9c6k1EOZa8cOb0L_9DGt7J-zp_YBWM_Y)
> 
> ![image](https://private-user-images.githubusercontent.com/63367722/345584031-2ce64f27-7383-4b31-be63-0f5027a95944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMzQyMDYsIm5iZiI6MTcyMDAzMzkwNiwicGF0aCI6Ii82MzM2NzcyMi8zNDU1ODQwMzEtMmNlNjRmMjctNzM4My00YjMxLWJlNjMtMGY1MDI3YTk1OTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE5MTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZTdiYzNkZDFhOWE4YjcxNzM5ODBjYWE1MzY2MzI1MjMwZTdlZmUzYjk4YjRiZjZiMDUxYTY2OTcwM2E5MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P7So7BIfx4N4qsDgobiD3gsiQkvLiozIk012ty1AV6o) second try also not worked ![image](https://private-user-images.githubusercontent.com/63367722/345584266-168e7b50-7c05-4a40-a601-b8602f766f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMzQyMDYsIm5iZiI6MTcyMDAzMzkwNiwicGF0aCI6Ii82MzM2NzcyMi8zNDU1ODQyNjYtMTY4ZTdiNTAtN2MwNS00YTQwLWE2MDEtYjg2MDJmNzY2Zjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE5MTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZjhhMWI0ZmVlN2E2YjRiYjBhY2I2NGExNTc1YjE5NjZhM2U0ODYzZmFkZDI3Y2YxMTkzMmVmZTk5NWM2OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WrQgaJ4-2exeJ83gMwv_gw7oG_URydGhR1Jg282WIXU)
> 
> thsi is not the only mod just as an example there are more

That is not relevant here, the information for display comes from the fabric.mod.json file, and on modrinth exists the version name.

Based on the week of the issue, the problem is with Windows. I don't have Windows devices right now so I can't debug it right now

**Comment by syorito-hatsuki** [comment]
![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/33298273/b88cc167-42d3-4f9c-bbbe-e7ef73df8579)

I have much to say, but... just... Windows suck!

**Comment by syorito-hatsuki** [comment]
> ![image](https://private-user-images.githubusercontent.com/27376947/342110576-5935de2f-7cb9-43c7-a1e0-5d28b5c6b4f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzUwODMsIm5iZiI6MTcyMDU3NDc4MywicGF0aCI6Ii8yNzM3Njk0Ny8zNDIxMTA1NzYtNTkzNWRlMmYtN2NiOS00M2M3LWExZTAtNWQyOGI1YzZiNGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAxMjYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOThkMDk2YjBkM2E1YjZkMTc2NWQ5OGM1NDRiMzQzOGIzMDc3NzVmMGJlMDZlNTRmYTY4NzA4MTVjYjY3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8WDSAMcucwsSZxcc7W5_F66NVBHlvIDnpKEHOCsVZ9g)
> 
> Steps to Reproduce:
> 
> Download C2ME version 0.2.0+alpha.11.98+1.21 Check for updates See output that suggests 0.2.0+alpha.11.104+1.21 Update all Reboot not required, check for updates See same output Check folder of your server mods ![image](https://private-user-images.githubusercontent.com/27376947/342110727-833e7a30-7405-4303-b9f2-a598d82a371f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzUwODMsIm5iZiI6MTcyMDU3NDc4MywicGF0aCI6Ii8yNzM3Njk0Ny8zNDIxMTA3MjctODMzZTdhMzAtNzQwNS00MzAzLWI5ZjItYTU5OGQ4MmEzNzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAxMjYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZDJkMDVjOTU1YWM4Yjk3ODVlZTJlYTBlNWZiZDc4MjM3MmE1MDJiMTdmMDVjYWQwNWE3NTUzYTNmNmVmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xxPmbf4YAll7xZKWwkRjQwtUZFjoX-zLSP7oJY1NqqQ) Notice there is probably a string parsing error going on (mod developers, amirite) Manually remove the .98 version Reboot Check for updates ![cmd_EH5hjHk3Nc](https://private-user-images.githubusercontent.com/27376947/342110754-f2f6b243-ef07-42ac-a535-fc0f89141848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzUwODMsIm5iZiI6MTcyMDU3NDc4MywicGF0aCI6Ii8yNzM3Njk0Ny8zNDIxMTA3NTQtZjJmNmIyNDMtZWYwNy00MmFjLWE1MzUtZmMwZjg5MTQxODQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAxMjYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzN2Q2MjU5MjU4MmVmZjgyNThlMzk2MmQ3NWNhMDQ5YmU1MjE2YmUwYzA3OTNiYjcyYTlhNTAwYTQ2ODMxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PKjoPMh6co_o7QNYxA6y1bBOiRy2NTtDQ5e6e87AkF4) Checks out tbh
> 
> Expected behavior: Same version name = Dont need to update
> 
> Notes: I'm guessing it's the + sign and perhaps a weird character inside there doing this

---
Windows is soo slow compare to Linux and Mac that it require increase Timeout time

> I have much to say, but... just... Windows suck!

**Comment by syorito-hatsuki** [comment]
Try a new update and reopen the issue if required
https://modrinth.com/mod/ducky-updater-rework/version/2024.7.1
