### ISSUE TITLE
Rename function

### ISSUE THREAD

**Issue by KIRUYXAN** [syorito-hatsuki/ducky-updater-rework#15]
Please add a function so that when updating mods can immediately change their names

**Comment by syorito-hatsuki** [comment]
Why and how do you imagine this?

**Comment by KIRUYXAN** [comment]
Well, personally, it’s just more convenient for me when the mods are named simply just the name and version, and you can do this, firstly, add in the config you can turn this function on and off, and secondly, when it updates the mods, the name of the mod is written in the chat, and you can write the desired name as a message and when downloading it will give the file this name

**Comment by monochromem1nd** [comment]
> Well, personally, it’s just more convenient for me when the mods are named simply just the name and version, and you can do this, firstly, add in the config you can turn this function on and off, and secondly, when it updates the mods, the name of the mod is written in the chat, and you can write the desired name as a message and when downloading it will give the file this name

Dude, did u even realize what u wrote?

**Comment by KIRUYXAN** [comment]
> > Well, personally, it’s just more convenient for me when the mods are named simply just the name and version, and you can do this, firstly, add in the config you can turn this function on and off, and secondly, when it updates the mods, the name of the mod is written in the chat, and you can write the desired name as a message and when downloading it will give the file this name
> 
> Dude, did u even realize what u wrote?

Yes, I understood perfectly what I wrote.
When this mod starts downloading the update file for the mod, with the renaming function enabled, it writes the name of the downloaded mod in the chat and you write the name you need for it in the form of a message, and this mod, when downloading the update file for the mod, gives it the name that you wrote in chat. 

Perhaps you can also try adding some selectors such as %name% and %version% which will be replaced with the mod name and version in the filename.

**Comment by monochromem1nd** [comment]
> > > Well, personally, it’s just more convenient for me when the mods are named simply just the name and version, and you can do this, firstly, add in the config you can turn this function on and off, and secondly, when it updates the mods, the name of the mod is written in the chat, and you can write the desired name as a message and when downloading it will give the file this name
> > 
> > 
> > Dude, did u even realize what u wrote?
> 
> Yes, I understood perfectly what I wrote. When this mod starts downloading the update file for the mod, with the renaming function enabled, it writes the name of the downloaded mod in the chat and you write the name you need for it in the form of a message, and this mod, when downloading the update file for the mod, gives it the name that you wrote in chat.
> 
> Perhaps you can also try adding some selectors such as %name% and %version% which will be replaced with the mod name and version in the filename.

For what?

**Comment by syorito-hatsuki** [comment]
Ye. I also don't understand why 🤔

**Comment by KIRUYXAN** [comment]
Well, it would just be more convenient for me
