### ISSUE TITLE
Since update to 1.21.1 it seems that Ducky Updater offers downgrade the mods and % file naming issue

### ISSUE THREAD

**Issue by cr-gomezm** [syorito-hatsuki/ducky-updater-rework#17]
Since 1.21.1 more and more mods got updated to include support for new minor update.

Sometimes when checking for updates and upon start, Ducky Updater states that a new version is available which indeed is a downgrade because of being marked for 1.21.1 and not 1.21 explicitly.

![image](https://github.com/user-attachments/assets/7b4bdcc0-2d50-4205-b88d-d51587765094)

Also when downloading files, if you have a manually downloaded file, the file naming is as per the filename in the download... when updating for first time using Ducky updater the file is downloaded but most of the time with % using html replacement for special characters.

This causes issues upon start with mod replacement.

![image](https://github.com/user-attachments/assets/9a6e91a1-c50e-4bcf-be72-75fa3662d73e)

**Comment by syorito-hatsuki** [comment]
Windows?

**Comment by cr-gomezm** [comment]
Windows Server Core LTSC2019 / JDK 21
MC 1.21 + Fabric Loader 0.16.5

**Comment by syorito-hatsuki** [comment]
So version names depends from how owner was marked it on Modrinth. It can mark 1.21.1 files as 1.21. % is just how url names are real encoded (browsers mostly just replace them, but I really didn't care about that cause it's change nothing in real 🫡)

**Comment by syorito-hatsuki** [comment]
https://modrinth.com/mod/ducky-updater-rework/version/2024.11.1
Fixed that Windows incorrect old mods removing
