### ISSUE TITLE
Unexpected Error trying to update mods by mod-ids

### ISSUE THREAD

**Issue by erengeez** [syorito-hatsuki/ducky-updater-rework#19]
![image](https://github.com/user-attachments/assets/2edd2ca4-5cc2-43b4-8d2f-b41c364ce43e)

The ids are correct.

Also it would be better to show the mod ids in the list of available updates, having to go through logs or open the mods as archives to read the `fabric.mod.json` files is quite annoying.

**Comment by syorito-hatsuki** [comment]
🫠

**Comment by syorito-hatsuki** [comment]
Ah. I get it. You forget to put the last argument true or false. That command works for adding and removing from ingnore
