### ISSUE TITLE
Modrinth ClientSide/ServerSide

### ISSUE THREAD

**Issue by tieb62** [syorito-hatsuki/ducky-updater-rework#2]
The mod's description states that the mod can be used on both sides independently, but the Modrinth "Sides" information states that it is "Unsupported" ClientSide and "Required" ServerSide.

I think that it should be put on "Optional" for both sides to help people find the mod more easily (e.g. if they filter ClientSide mods).

**Comment by syorito-hatsuki** [comment]
Ye. I think that I work on client but yesterday I realize that it didn't so I changed it on Modrinth and will be return after fix

**Comment by tieb62** [comment]
Alright, should I leave this issue opened until the deployment of the fix or should I close it now ?

**Comment by syorito-hatsuki** [comment]
I leave it open. That allows us to not forget to fix it :)
I can't fix it right now because it requires architecture refactoring, but currently, I have another project ongoing.

**Comment by tieb62** [comment]
Any news ?

**Comment by syorito-hatsuki** [comment]
The latest news I publish on my Discord every first week of month (if news exists). Here the latest and if interest here discord invite link https://discord.gg/pbwnMwnUD6
![image](https://github.com/syorito-hatsuki/ducky-updater/assets/33298273/0df28011-6f29-40ba-b1ec-7dc632f67901)

**Comment by tt-thoma** [comment]
Wait, so #7 is a glitch ? Because it cannot update mods in the client at all

**Comment by syorito-hatsuki** [comment]
> Wait, so #7 is a glitch ? Because it cannot update mods in the client at all

The first versions worked with clients, but then I broke it because I wrote this mod just quickly for a friend. And now the mod is planned to be rewritten next year and release the next update/remake with all the features that I promise on Discord: https://discord.gg/pbwnMwnUD6
![image](https://github.com/syorito-hatsuki/ducky-updater/assets/33298273/3f35d6d4-8a29-4523-a199-546f08ca905a)

**Comment by syorito-hatsuki** [comment]
Fixed in https://github.com/syorito-hatsuki/ducky-updater-rework/pull/10, soon will be uploaded to Modrinth and CurseForge
