### ISSUE TITLE
Curseforge

### ISSUE THREAD

**Issue by suerion** [syorito-hatsuki/ducky-updater-rework#21]
Hey, does Durw not fetch updates from curseforge anymore? I had a few curseforge exlusive mods in my modpack, but they are not checked from your mod? Could you look on this, if we get all official Modsites? 

Hope so

**Comment by syorito-hatsuki** [comment]
DURW never checked CF updates. Only Modrinth.

Reason: CurseForge API is shit

**Comment by suerion** [comment]
Omly because CF is shit, it has also mods exclusiv. It work with the murmur. Hash without problem. But okey

**Comment by syorito-hatsuki** [comment]
> Omly because CF is shit, it has also mods exclusiv. It work with the murmur. Hash without problem. But okey

Second reason, CF disallow me to publish DURW on their platform 🧨

**Comment by suerion** [comment]
Really, they mod politic is so 🐑, they had not learned about the sodium protest...

**Comment by syorito-hatsuki** [comment]
Addition for anyone how gonna read this
![Image](https://github.com/user-attachments/assets/49120fe0-770d-47c2-b050-29d27c4cddad)
