### ISSUE TITLE
du check-for-updates turns server text green 

### ISSUE THREAD

**Issue by kiven7e** [syorito-hatsuki/ducky-updater-rework#4]
the command `/du check-for-updates ` turns the rest of a server console to green
![image](https://github.com/syorito-hatsuki/ducky-updater/assets/32518935/92413777-a922-40ec-9943-c595f2658f0c)
also on modrinth it says the command is `/du chech-for-updates`

**Comment by syorito-hatsuki** [comment]
Oh, ye. Looks like I forget to add RESET for colors in 2 messages. But currently, I don't have the possibility to fix it. And next update will be full refactor.
https://github.com/syorito-hatsuki/ducky-updater/blob/686384774f597ca5819b74f11a05b8ce2beb44ec/src/main/kotlin/dev/syoritohatsuki/duckyupdater/util/Ansi.kt#L23-L24

Like in other
https://github.com/syorito-hatsuki/ducky-updater/blob/686384774f597ca5819b74f11a05b8ce2beb44ec/src/main/kotlin/dev/syoritohatsuki/duckyupdater/util/Ansi.kt#L14-L22

**Comment by syorito-hatsuki** [comment]
Should be fixed in https://github.com/syorito-hatsuki/ducky-updater-rework/pull/10, soon will be uploaded to Modrinth and CurseForge. But if I again miss somewhere reopen
