### ISSUE TITLE
most of the updates are just a different lable not a seperate version

### ISSUE THREAD

**Issue by kiven7e** [syorito-hatsuki/ducky-updater-rework#5]
![image](https://github.com/syorito-hatsuki/ducky-updater/assets/32518935/759f43b7-4874-4329-868c-4866e9e62bec)

**Comment by syorito-hatsuki** [comment]
https://github.com/syorito-hatsuki/ducky-updater/issues/1#issuecomment-1585631678

**Comment by syorito-hatsuki** [comment]
Fixed in https://github.com/syorito-hatsuki/ducky-updater-rework/pull/10, soon will be uploaded to Modrinth and CurseForge
