### ISSUE TITLE
Make the "server side" information clearer on modrinth

### ISSUE THREAD

**Issue by tt-thoma** [syorito-hatsuki/ducky-updater-rework#7]
There is very little indication of this mod being server-side only on the modrinth's launcher page, with the only "server" indication being really tiny. On the website, you also can scroll down to the technical tab to find a little less subtle tab, but not really visible at first sight.

On the launcher:
![image](https://github.com/syorito-hatsuki/ducky-updater/assets/72872981/7dc60ecd-a0ba-496f-88b4-e5b97d61cf14)

On the website:
![image](https://github.com/syorito-hatsuki/ducky-updater/assets/72872981/c28b2a17-c669-45df-ab0b-759f584f1b1f)

You could add something like a **`this mod does not work client-side!`** indicator at the top of the desc to make sure no one installs/uses it by accident on a client

**Comment by syorito-hatsuki** [comment]
All questions to Modrinth designers🙃

**Comment by tt-thoma** [comment]
Can't you just put "This is a server-side mod" at the top of the description ? Doesn't sound like a big deal

**Comment by syorito-hatsuki** [comment]
![image](https://github.com/syorito-hatsuki/ducky-updater-rework/assets/33298273/cceb4755-0428-47b5-9398-d38594a09260)


> Can't you just put "This is a server-side mod" at the top of the description ? Doesn't sound like a big deal

Description... And yes it big deal because next update gonna add support for both side

**Comment by tt-thoma** [comment]
Okay

**Comment by syorito-hatsuki** [comment]
Fixed in https://github.com/syorito-hatsuki/ducky-updater-rework/pull/10, soon will be uploaded to Modrinth and CurseForge
